/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export const MXT_001_TEMPLATE = `
<article class="mx-result mx-theme-{theme} MXT_001" data-template="MXT_001" data-use-case="{uc_id}">
  <header class="mx-result-header">
    <h1 class="mx-result-title">{title}</h1>
    <p class="mx-result-subtitle">{subtitle}</p>
    <div class="mx-stats">
      {stats}
    </div>
  </header>
  <main class="mx-result-body">
    {blocks}
  </main>
  <footer class="mx-footer">
    <p>MX-Grade Report • Generated by MarketXtractor v3</p>
  </footer>
</article>
`;
